<?php

namespace Database\Seeders;

use App\Models\Player;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FootbalerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $gladbach = [
            [
                'club_id' => 3,
                'name' => 'Jonas Omlin',
                'slug' => 'jonas-omlin',
                'position_id' => 1,
                'shirt_number' => 1,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Moritz Nicolas',
                'slug' => 'moritz-nicolas',
                'position_id' => 1,
                'shirt_number' => 33,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Tobias Sippel',
                'slug' => 'tobias-sippel',
                'position_id' => 1,
                'shirt_number' => 21,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Fabio Chiarodia',
                'slug' => 'fabio-chiarodia',
                'position_id' => 2,
                'shirt_number' => 2,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Marvin Friedrich',
                'slug' => 'marvin-friedrich',
                'position_id' => 2,
                'shirt_number' => 5,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Luca Netz',
                'slug' => 'luca-netz',
                'position_id' => 2,
                'shirt_number' => 20,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Lukas Ullrich',
                'slug' => 'lukas-ullrich',
                'position_id' => 2,
                'shirt_number' => 26,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Nico Elvedi',
                'slug' => 'nico-elvedi',
                'position_id' => 2,
                'shirt_number' => 30,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Ko Itakura',
                'slug' => 'ko-itakura',
                'position_id' => 2,
                'shirt_number' => 3,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Stefan Lainer',
                'slug' => 'stefan-lainer',
                'position_id' => 2,
                'shirt_number' => 18,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Tony Jantschke',
                'slug' => 'tony-jantschke',
                'position_id' => 2,
                'shirt_number' => 24,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Joe Scally',
                'slug' => 'joe-scally',
                'position_id' => 2,
                'shirt_number' => 29,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Maximilian Wöber',
                'slug' => 'maximilian-wöber',
                'position_id' => 2,
                'shirt_number' => 39,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Julian Weigl',
                'slug' => 'julian-weigl',
                'position_id' => 3,
                'shirt_number' => 8,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Florian Neuhaus',
                'slug' => 'florian-neuhaus',
                'position_id' => 3,
                'shirt_number' => 10,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Manu Koné',
                'slug' => 'manu-koné',
                'position_id' => 3,
                'shirt_number' => 17,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Christoph Kramer',
                'slug' => 'christoph-kramer',
                'position_id' => 3,
                'shirt_number' => 23,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Franck Honorat',
                'slug' => 'franck-honorat',
                'position_id' => 3,
                'shirt_number' => 9,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Hannes Wolf',
                'slug' => 'hannes-wolf',
                'position_id' => 3,
                'shirt_number' => 11,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Nathan Ngoumou',
                'slug' => 'nathan-ngoumou',
                'position_id' => 3,
                'shirt_number' => 19,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Robin Hack',
                'slug' => 'robin-hack',
                'position_id' => 3,
                'shirt_number' => 25,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Rocco Reitz',
                'slug' => 'rocco-reitz',
                'position_id' => 3,
                'shirt_number' => 27,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],  
            [
                'club_id' => 3,
                'name' => 'Patrick Herrmann',
                'slug' => 'patrick-herrmann',
                'position_id' => 4,
                'shirt_number' => 7,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Alassane Pléa',
                'slug' => 'alassane-pléa',
                'position_id' => 4,
                'shirt_number' => 14,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Jordan',
                'slug' => 'jordan',
                'position_id' => 4,
                'shirt_number' => 13,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ], 
            [
                'club_id' => 3,
                'name' => 'Tomáš Čvančara',
                'slug' => 'tomáš-cvančara',
                'position_id' => 4,
                'shirt_number' => 31,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 3,
                'name' => 'Grant-Leon Ranos',
                'slug' => 'grant-leon-ranos',
                'position_id' => 4,
                'shirt_number' => 28,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            
            
        ];

        $leverkusen = [
            [
                'club_id' => 1,
                'name' => 'Lukáš Hrádecký',
                'slug' => 'lukáš-hrádecký',
                'position_id' => 1,
                'shirt_number' => 1,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Matej Kovar',
                'slug' => 'matej-kovar',
                'position_id' => 1,
                'shirt_number' => 17,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Niklas Lomb',
                'slug' => 'niklas-lomb',
                'position_id' => 1,
                'shirt_number' => 36,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Josip Stanisic',
                'slug' => 'josip-stanisic',
                'position_id' => 2,
                'shirt_number' => 2,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Piero Hincapie',
                'slug' => 'piero-hincapie',
                'position_id' => 2,
                'shirt_number' => 3,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Jonathan Tah',
                'slug' => 'jonathan-tah',
                'position_id' => 2,
                'shirt_number' => 4,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Odilon Kossounou',
                'slug' => 'odilon-kossounou',
                'position_id' => 2,
                'shirt_number' => 6,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Edmond Tapsoba',
                'slug' => 'edmond-tapsoba',
                'position_id' => 2,
                'shirt_number' => 12,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Arthur',
                'slug' => 'arthur',
                'position_id' => 2,
                'shirt_number' => 13,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Alejandro Grimaldo',
                'slug' => 'alejandro-grimaldo',
                'position_id' => 2,
                'shirt_number' => 20,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Timothy Fosu-Mensah',
                'slug' => 'timothy-fosu-mensah',
                'position_id' => 2,
                'shirt_number' => 24,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Jeremie Frimpong',
                'slug' => 'jeremie-frimpong',
                'position_id' => 2,
                'shirt_number' => 30,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Madi Monamay',
                'slug' => 'madi-monamay',
                'position_id' => 3,
                'shirt_number' => 31,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Jonas Hofmann',
                'slug' => 'jonas-hofmann',
                'position_id' => 3,
                'shirt_number' => 7,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Robert Andrich',
                'slug' => 'robert-andrich',
                'position_id' => 3,
                'shirt_number' => 8,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Florian Wirtz',
                'slug' => 'florian-wirtz',
                'position_id' => 3,
                'shirt_number' => 10,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Nadiem Amiri',
                'slug' => 'nadiem-amiri',
                'position_id' => 3,
                'shirt_number' => 11,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Noah Mbamba',
                'slug' => 'noah-mbamba',
                'position_id' => 3,
                'shirt_number' => 18,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Exequiel Palacios',
                'slug' => 'exequiel-palacios',
                'position_id' => 4,
                'shirt_number' => 25,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Gustavo Puerta',
                'slug' => 'gustavo-puerta',
                'position_id' => 4,
                'shirt_number' => 32,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Granit Xhaka',
                'slug' => 'granit-xhaka',
                'position_id' => 4,
                'shirt_number' => 34,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ], 
            [
                'club_id' => 1,
                'name' => 'Ayman Aourir',
                'slug' => 'ayman-aourir',
                'position_id' => 4,
                'shirt_number' => 47,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Patrik Schick',
                'slug' => 'patrik-schick',
                'position_id' => 4,
                'shirt_number' => 14,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Nathan Tella',
                'slug' => 'nathan-tella',
                'position_id' => 4,
                'shirt_number' => 19,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ], 
            [
                'club_id' => 1,
                'name' => 'Amine Adli',
                'slug' => 'amine-adli',
                'position_id' => 4,
                'shirt_number' => 21,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Victor Boniface',
                'slug' => 'victor-boniface',
                'position_id' => 4,
                'shirt_number' => 22,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 1,
                'name' => 'Adam Hlozek',
                'slug' => 'adam-hlozek',
                'position_id' => 4,
                'shirt_number' => 23,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ], 
            
        ];
        //
        $werder = [
            [
                'club_id' => 14,
                'name' => 'Jiri Pavlenka',
                'slug' => 'jiri-pavlenka',
                'position_id' => 1,
                'shirt_number' => 1,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Michael Zetterer',
                'slug' => 'michael-zetterer',
                'position_id' => 1,
                'shirt_number' => 30,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Eduardo Dos Santos Haesler',
                'slug' => 'eduardo-dos-santos-haesler',
                'position_id' => 1,
                'shirt_number' => 38,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Anthony Jung',
                'slug' => 'anthony-jung',
                'position_id' => 2,
                'shirt_number' => 3,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Amos Pieper',
                'slug' => 'amos-pieper',
                'position_id' => 2,
                'shirt_number' => 5,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Miloš Veljković',
                'slug' => 'miloš-veljković',
                'position_id' => 2,
                'shirt_number' => 13,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Marco Friedl',
                'slug' => 'marco-friedl',
                'position_id' => 2,
                'shirt_number' => 32,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Niklas Stark',
                'slug' => 'niklas-stark',
                'position_id' => 2,
                'shirt_number' => 4,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Mitchell Weiser',
                'slug' => 'mitchell-weiser',
                'position_id' => 2,
                'shirt_number' => 8,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Felix Agu',
                'slug' => 'felix-agu',
                'position_id' => 2,
                'shirt_number' => 27,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Christian Groß',
                'slug' => 'christian-groß',
                'position_id' => 2,
                'shirt_number' => 36,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Olivier Deman',
                'slug' => 'olivier-deman',
                'position_id' => 3,
                'shirt_number' => 2,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Leonardo Bittencourt',
                'slug' => 'leonardo-bittencourt',
                'position_id' => 3,
                'shirt_number' => 10,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Naby Keïta',
                'slug' => 'naby-keïta',
                'position_id' => 3,
                'shirt_number' => 18,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Nicolai Rapp',
                'slug' => 'nicolai-rapp',
                'position_id' => 3,
                'shirt_number' => 23,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Jens Stage',
                'slug' => 'jens-stage',
                'position_id' => 3,
                'shirt_number' => 6,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Senne Lynen',
                'slug' => 'senne-lynen',
                'position_id' => 3,
                'shirt_number' => 14,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Romano Schmid',
                'slug' => 'romano-schmid',
                'position_id' => 3,
                'shirt_number' => 20,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Leon Opitz',
                'slug' => 'leon-opitz',
                'position_id' => 3,
                'shirt_number' => 35,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Marvin Ducksch',
                'slug' => 'marvin-ducksch',
                'position_id' => 4,
                'shirt_number' => 7,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Justin Njinmah',
                'slug' => 'justin-njinmah',
                'position_id' => 4,
                'shirt_number' => 17,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ], 
            [
                'club_id' => 14,
                'name' => 'Nick Woltemade',
                'slug' => 'nick-woltemade',
                'position_id' => 4,
                'shirt_number' => 29,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Dawid Kownacki',
                'slug' => 'dawid-kownacki',
                'position_id' => 4,
                'shirt_number' => 9,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ],
            [
                'club_id' => 14,
                'name' => 'Rafael Borré',
                'slug' => 'rafael-borré',
                'position_id' => 4,
                'shirt_number' => 19,
                'status' => 'active',
                'created_at' => Carbon::now(),
            ], 
           
        ];

        Player::insert($werder);
        Player::insert($leverkusen);
        Player::insert($gladbach);

    }
}
